services:

  postgres-auth:
    image: postgres:16-alpine
    container_name: postgres-auth
    environment:
      POSTGRES_DB: authdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
    ports:
      - "5433:5432"
    volumes:
      - auth-data:/var/lib/postgresql/data
    networks:
      - clinic-network

  postgres-patient:
    image: postgres:16-alpine
    container_name: postgres-patient
    environment:
      POSTGRES_DB: patientdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
    ports:
      - "5434:5432"
    volumes:
      - patient-data:/var/lib/postgresql/data
    networks:
      - clinic-network

  postgres-doctor:
    image: postgres:16-alpine
    container_name: postgres-doctor
    environment:
      POSTGRES_DB: doctordb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
    ports:
      - "5435:5432"
    volumes:
      - doctor-data:/var/lib/postgresql/data
    networks:
      - clinic-network

  postgres-appointment:
    image: postgres:16-alpine
    container_name: postgres-appointment
    environment:
      POSTGRES_DB: appointmentdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
    ports:
      - "5436:5432"
    volumes:
      - appointment-data:/var/lib/postgresql/data
    networks:
      - clinic-network

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"     # Porta para apps
      - "15672:15672"   # Interface Web
    networks:
      - clinic-network

  zipkin:
    image: openzipkin/zipkin
    container_name: zipkin
    ports:
      - "9411:9411"
    networks:
      - clinic-network

networks:
  clinic-network:
    driver: bridge

volumes:
  auth-data:
  patient-data:
  doctor-data:
  appointment-data:
